language: R

apt_packages:
  - r-cran-rjava

before_install:
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -y npm
#  - sudo R CMD javareconf

install:
  - npm install -g grunt-cli bower
  - npm install -g simplehttpserver
  - pip install ansible

before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
  - cd R && Rscript run-heatmap.R && Rscript run-all.R && cd ..
  - simplehttpserver web/ > /dev/null & #shooting up a web server for the tests
  - sleep 15

script:
  - casperjs test web/tests/test.js
  - ansible-playbook -i ansible/tests/inventory ansible/playbook.yml --syntax-check
  - ansible-playbook -i ansible/tests/inventory ansible/playbook.yml --connection=local --sudo

# whitelist
branches:
  only:
    - master
    - develop
    - travis
