language: R

apt_packages:
  - r-cran-rjava

before_install:
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -y npm
#  - sudo R CMD javareconf

install:
  - npm install -g grunt-cli bower
  - npm install -g simplehttpserver

before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
  - cd R && Rscript run-heatmap.R && Rscript run-all.R
  - simplehttpserver web/ & #shooting up a web server for the tests

script: pwd && cd .. && casperjs test web/tests/test.js

# whitelist
branches:
  only:
    - master
    - develop
    - travis
