language: R
dist: trusty

apt_packages:
  - r-cran-rjava
  - lynx

env:
  global:
    - NETLIFYAPIKEY=abc123
    - HEATMAP_HEALTHCHECK=http://example.com

addons:
  hosts:
    - hoyodesmog.diegovalle.net

before_install:
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -y npm
  - sudo apt-get install -y lynx
  - sudo apt-get install -y r-cran-rjava
  - "export PHANTOMJS_VERSION=2.1.1"
  - "phantomjs --version"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "phantomjs --version"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"

install:
  - npm install -g grunt-cli bower
  - npm install -g simplehttpserver
  - sudo pip install ansible

before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
  - export ANSIBLE_HOST_KEY_CHECKING=False; ansible-playbook -i ansible/tests/inventory ansible/playbook.yml --syntax-check
  - ansible-playbook -i ansible/tests/inventory ansible/playbook.yml --connection=local --become --extra-vars "testing=true"
  - simplehttpserver web/ > /dev/null & #shooting up a web server for the tests
  - sleep 30

script:
  - cd R && sudo -u deploy ./run-heatmap.sh && cd ..
  - casperjs test web/tests/test.js
  - curl -kLv http://hoyodesmog.diegovalle.net | grep 'Real-Time Mexico'

# whitelist
branches:
  only:
    - master
    - develop
    - travis
