language: R
dist: trusty

apt_packages:
  - r-cran-rjava
  - lynx

env:
  global:
    - NETLIFYAPIKEY=abc123
    - HEATMAP_HEALTHCHECK=http://example.com

addons:
  hosts:
    - hoyodesmog.diegovalle.net

before_install:
  - git submodule update --init --recursive
  - sudo apt-get -qq update
  - sudo apt-get install -y npm
  - sudo apt-get install -y lynx
  - sudo apt-get install -y r-cran-rjava
#  - sudo R CMD javareconf

install:
  - npm install -g grunt-cli bower
  - npm install -g simplehttpserver
  - sudo pip install ansible

before_script:
  - npm install -g casperjs
  - phantomjs --version; casperjs --version
  - export ANSIBLE_HOST_KEY_CHECKING=False; ansible-playbook -i ansible/tests/inventory ansible/playbook.yml --syntax-check
  - ansible-playbook -i ansible/tests/inventory ansible/playbook.yml --connection=local --become --extra-vars "testing=true"
  - simplehttpserver /var/www/hoyodesmog.diegovalle.net/web/ > /dev/null & #web server for the tests
  - sleep 30

script:
  - sudo -u deploy /var/www/hoyodesmog.diegovalle.net/R/run-heatmap.sh
  - sudo -u deploy casperjs test /var/www/hoyodesmog.diegovalle.net/web/tests/test.js
  - curl -kLv http://hoyodesmog.diegovalle.net | grep 'Real-Time Mexico'

# whitelist
branches:
  only:
    - master
    - develop
    - travis
