# fly.toml

app = "hoyodesmog"
primary_region = "lax"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
  
[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

