- name: Install npm
  apt: name="{{ item }}" state=latest
  with_items:
    - npm
    - nodejs
    - nodejs-legacy

- name: Install netlify-cli
  npm:  name=netlify-cli global=yes

#- name: Create soft link
#  shell: ln -s $(which nodejs) /usr/bin/node

- name: print to stdout
  command: netlify
  register: nout

- debug: msg="{{ nout.stdout }}"

- debug: msg="{{ nout.stderr }}"

