- name: Install npm
  apt: name="{{ item }}" state=latest
  with_items:
    - npm
    - nodejs

- name: Install netlify-cli
  npm:  name=netlify-cli global=yes

- name: print to stdout
  command: echo $(netlify)
  register: hello

- debug: msg="{{ hello.stdout }}"

- debug: msg="{{ hello.stderr }}"

- name: Create soft link
  command: ln -s $(which nodejs) /usr/bin/node