---
r_repository:
  - type: deb
    url: "https://cloud.r-project.org/bin/linux/ubuntu  {{ ansible_distribution_release }}/"
r_packages: ['r-base', 'r-base-dev',
             'r-cran-rjava', 'curl',
             'libxml2-dev',
             'r-cran-xml',
             'libgdal-dev', 'libproj-dev']
install_packages: true
