# Postfix

- name: Installs postfix mail server
  apt: pkg=postfix state=installed update_cache=true
  notify:
    - start postfix

- name: Copy virtual-regexp for postfix (send all mail to myself)
  copy: src=config/virtual-regexp dest=/etc/postfix/virtual-regexp
  notify:
    - postmap virtual-regexp

- name: Sendgrid authentication info
  lineinfile:
    dest: /etc/postfix/sendgrid_passwd
    line: "[smtp.sendgrid.net]:587 {{SENDGRID_USER}}:{{SENDGRID_PASS}}"
    create: True
    owner: root
    group: root
    mode: 0644
  notify:
    - postmap virtual
    - postmap sendgrid_passwd

- name: Postfix + sendgrid
  register: sendgrid
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^smtp_sasl_auth_enable =', line: 'smtp_sasl_auth_enable = yes' }
    - { regexp: '^smtp_sasl_password_maps =', line: 'smtp_sasl_password_maps = hash:/etc/postfix/sendgrid_passwd' }
    - { regexp: '^smtp_sasl_security_options =', line: 'smtp_sasl_security_options = noanonymous' }
    - { regexp: '^smtp_tls_security_level =', line: 'smtp_tls_security_level = encrypt' }
    - { regexp: '^header_size_limit =', line: 'header_size_limit = 4096000' }
    - { regexp: '^relayhost =', line: 'relayhost = [smtp.sendgrid.net]:587' }
    - { regexp: '^inet_interfaces =', line: 'inet_interfaces = loopback-only' }
    - { regexp: '^virtual_maps =', line: 'virtual_maps = hash:/etc/postfix/virtual, regexp:/etc/postfix/virtual-regexp' }
  notify:
    - Restart postfix
