# Install nginx

- name: add apt-key
  shell: curl https://nginx.org/keys/nginx_signing.key | /usr/bin/apt-key add - warning=false

- name: modify repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://nginx.org/packages/mainline/ubuntu/ {{ansible_distribution_release}} nginx"
    - "deb-src http://nginx.org/packages/mainline/ubuntu/ {{ansible_distribution_release}} nginx"

- name: install openssl
  apt:
    name: openssl
    state: present

- name: Install nginx
  apt:
    name: nginx
    state: present
    force: yes
  notify: Restart nginx

- name: Ensure that nginx snippets dir exists
  file:
    path: "/etc/nginx/snippets/"
    state: directory
    owner: "root"
    group: "root"
    mode: "0644"

- name: Generate useful snippets
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/snippets/{{ item }}"
  with_items:
    - referral-spam.conf
    - acme-challenge.conf
  notify: Restart nginx


- name: Copy over h5bp configuration
  copy: src={{ item }} dest=/etc/nginx/{{ item }}
  with_items:
    - h5bp/
    - mime.types

- name: copy nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart nginx

- name: verify /etc/nginx/sites-enabled/ exists
  file: path=/etc/nginx/sites-enabled/ state=directory owner=root group=root mode=0700

- name: Copy over website configuration
  copy: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item }}
  with_items:
    - ssl.no-default
    - no-default
  notify: Restart nginx


