- name: Install npm
  apt: name="{{ item }}" state=latest
  with_items:
    - npm
    - nodejs

- name: Install netlify-cli
  npm:  name=netlify-cli global=yes

- name: print to stdout
  action: command echo $(which nodejs)

- name: Create soft link
  command: ln -s $(which nodejs) /usr/bin/node