- name: Install npm
  apt: name="{{ item }}" state=latest
  with_items:
    - npm
    - node

- name: Install netlify-cli
  npm:  name=netlify-cli global=yes

- name: Install netlifly
  file:
    src: /usr/bin/node
    dest: /usr/bin/nodejs
    state: link