# ansible-playbook playbook.yml --ask-vault-pass

---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: hoyodesmog
  vars:
    testing: 'false'
    deploy_user_name: deploy
    deploy_public_keys:
      - vps.pub
    r_repository:
      - type: deb
        url: "http://cran.rstudio.com/bin/linux/ubuntu  {{ ansible_distribution_release }}/"
    nginx_user: www-data
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    letsencrypt_user: letsencrypt
    letsencrypt_group: letsencrypt
    letsencrypt_cronjob_daysofmonth: 1

  pre_tasks:
    # for the structure of secrets.yml see secrets-test.yml
    - name: Load secrets
      when: testing != 'true'
      include_vars: secrets.yml
      no_log: true

    - name: Load secrets (test version)
      when: testing == 'true'
      include_vars: secrets-test.yml
      no_log: true

  roles:
    - setup
    - R
    - nginx
    - letsencrypt
    - sendgrid
    - hoyodesmog-nginx
    - netlifly
    - hoyodesmog
