- name: Copy over letsencrypt certs
  when: testing == 'false'
  copy: content={{ item.src }} dest=/{{ item.dest }}
  with_items:
    - {src: "{{domain_csr}}", dest: /etc/nginx/ssl/hoyodesmog.diegovalle.net/domain.csr}
    - {src: "{{account_key}}", dest: /etc/nginx/ssl/hoyodesmog.diegovalle.net/account.key}
    - {src: "{{domain_key}}", dest: /etc/nginx/ssl/hoyodesmog.diegovalle.net/domain.key}
    - {src: "{{chained_pem}}", dest: /etc/nginx/ssl/hoyodesmog.diegovalle.net/chained.pem}
  notify: Restart nginx

- name: Copy over website configuration
  copy: src={{ item }} dest=/etc/nginx/sites-enabled/{{ item }}
  with_items:
    - hoyodesmog.diegovalle.net
  notify: Restart nginx

- name: add cron entry to renew cert
  cron:
    name="renew hoyodesmog.diegovalle.net certificate"
    minute="30"
    day="11"
    hour="3"
    job="/home/{{ letsencrypt_user }}/ssl/renew_cert.sh hoyodesmog.diegovalle.net && curl -fsS --retry 3 {{ HEALTH_CHECK_LETSENCRYPT_HOYODEMOSG }}  > /dev/null"
  vars:
    ansible_ssh_pipelining: true
    become: yes
    become_user: "{{letsencrypt_user}}"