---
- name: Ensure group "radmin" exists
  group:
    name: radmin
    state: present

- name: adding existing user "{{ deploy_user_name }}" to group radmin
  user:
    name: "{{ deploy_user_name }}"
    groups: radmin
    append: yes

- name: Add R repository public key
  apt_key:
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9
    keyserver: keyserver.ubuntu.com
    state: present

- name: Add R repository
  apt_repository:
    repo: "{{ item.type }} {{ item.url }}"
    state: present
    update_cache: true
  with_items: "{{ r_repository }}"

- name: add rrutter ppa
  apt_repository:
    repo: ppa:marutter/rrutter4.0
    update_cache: yes

- name: add c2d4u repository
  apt_repository:
    repo: ppa:marutter/c2d4u4.0+
    update_cache: yes

- name: Install Packages
  apt: name="{{ packages }}" state=latest
  vars:
    packages:
      - r-base
      - r-recommended
      - r-cran-rjava
      - r-cran-xml
      - r-cran-catools
      - r-base-dev
      - libxml2-dev
      - libgdal-dev
      - libproj-dev
      - libssl-dev
      - software-properties-common

- name: Creates .Rprofile with default repo
  lineinfile: dest=/home/{{deploy_user_name}}/.Rprofile line='local({r <- getOption("repos");r["CRAN"] <- "https://mran.revolutionanalytics.com/snapshot/2020-07-31";options(repos = r)})' create=True
  vars:
    ansible_ssh_pipelining: true
  become: yes
  become_user: "{{deploy_user_name}}"

#- name: Creates .Rprofile with default repo
#  lineinfile: dest=/home/{{deploy_user_name}}/.Renviron line='R_LIBS_SITE=/home/{{deploy_user_name}}/R/rpackages' create=True

- name: Creates user R package directory
  file: path=/home/{{deploy_user_name}}/R/rpackages state=directory  owner={{deploy_user_name}} group={{deploy_user_name}}

- name: Creates .Rprofile with default repo
  lineinfile: dest=/root/.Rprofile line='local({r <- getOption("repos");r["CRAN"] <- "https://mran.revolutionanalytics.com/snapshot/2020-07-31";options(repos = r)})' create=True

- name: Ensure /usr/local/lib/R/site-library/ is writable by radmin
  file: dest=/usr/local/lib/R/site-library/ owner=root group=radmin mode=u=rwX,g=rwX,o=rX recurse=yes

# : ${R_JAVA_LD_LIBRARY_PATH=${JAVA_HOME}/jre/lib/amd64/server}
- name: Config java
  command: R CMD javareconf

- name: print to stdout
  command: "Rscript -e '.libPaths()'"
  register: rout

- debug: msg="{{ rout.stdout }}"
